# WARNING: Under review - generated by LLM.

from types import SimpleNamespace

import mlx.core as mx
import pytest

from .tiny_llm_base import (
    AgentLimits,
    ToolAction,
    generate_response,
    initial_messages,
    run_agent,
)


class FakeWorkspace:
    """Minimal Day 1 tool boundary; later days implement the real workspace."""

    def __init__(self, root):
        self.policy = SimpleNamespace(
            root=root, allow_writes=False, allowed_commands=()
        )
        self.available_tools = frozenset({"read_file"})
        self.modified_files = set()
        self.executed = []

    def execute(self, action):
        self.executed.append(action)
        return "README contents"


def responses(*items):
    """Return scripted model responses for loop behavior tests."""

    queue = iter(items)
    return lambda messages: next(queue)


def test_task_1_initial_messages_preserve_the_task():
    messages = initial_messages("inspect the project", "system instructions")

    assert messages == [
        {"role": "system", "content": "system instructions"},
        {"role": "user", "content": "inspect the project"},
    ]


def test_task_1_rejects_an_empty_task():
    try:
        initial_messages("   ", "system instructions")
    except ValueError as error:
        assert "must not be empty" in str(error)
    else:
        assert False, "expected an empty task to be rejected"


def test_task_2_executes_a_tool_appends_its_result_and_finishes():
    workspace = FakeWorkspace("/tmp")
    responses_queue = iter(
        [
            '{"tool":"read_file","path":"README.md"}',
            '{"final":"inspected README"}',
        ]
    )

    result = run_agent(
        "inspect the project", lambda messages: next(responses_queue), workspace
    )

    assert result.completed
    assert result.reason == "completed"
    assert result.final == "inspected README"
    assert workspace.executed == [ToolAction("read_file", {"path": "README.md"})]


def test_task_3_returns_invalid_and_unknown_actions_to_the_model():
    workspace = FakeWorkspace("/tmp")
    responses_queue = iter(
        [
            "not json",
            '{"tool":"run_shell","argv":["rm","-rf","."]}',
            '{"final":"recovered"}',
        ]
    )

    result = run_agent(
        "inspect the project", lambda messages: next(responses_queue), workspace
    )

    assert result.completed
    assert workspace.executed == []
    assert [event.action for event in result.events[:2]] == [None, None]
    assert all(event.result.startswith("error:") for event in result.events[:2])


def test_task_4_stops_at_the_step_budget():
    workspace = FakeWorkspace("/tmp")

    result = run_agent(
        "inspect the project",
        lambda _messages: '{"tool":"read_file","path":"README.md"}',
        workspace,
        AgentLimits(max_steps=2, max_identical_actions=3),
    )

    assert not result.completed
    assert result.reason == "step_limit"
    assert len(result.events) == 2
    assert len(workspace.executed) == 2


def test_task_5_agent_observes_then_finishes():
    workspace = FakeWorkspace("/tmp")
    generate = responses(
        '{"tool":"read_file","path":"README.md"}',
        '{"final":"inspected README"}',
    )

    result = run_agent("inspect the project", generate, workspace)

    assert result.completed
    assert result.final == "inspected README"
    assert result.reason == "completed"
    assert len(result.events) == 2


def test_task_6_agent_recovers_from_invalid_json():
    workspace = FakeWorkspace("/tmp")
    generate = responses("not json", '{"final":"recovered"}')

    result = run_agent("inspect the project", generate, workspace)

    assert result.completed
    assert result.events[0].result.startswith("error:")


def test_task_7_agent_stops_repeated_actions():
    workspace = FakeWorkspace("/tmp")
    generate = responses(*['{"tool":"read_file","path":"README.md"}'] * 3)

    result = run_agent(
        "inspect the project",
        generate,
        workspace,
        AgentLimits(max_steps=5, max_identical_actions=2),
    )

    assert not result.completed
    assert result.reason == "repeated_action_limit"


def _assert_exact_observation_payload(run_agent_impl):
    workspace = FakeWorkspace("/tmp")
    seen = []

    def generate(messages):
        seen.append([dict(message) for message in messages])
        if len(seen) == 1:
            return '{"tool":"read_file","path":"README.md"}'
        return '{"final":"done"}'

    result = run_agent_impl("inspect", generate, workspace)

    assert result.completed
    assert seen[1][-1] == {
        "role": "user",
        "content": "Tool result:\nREADME contents",
    }, "the exact tool-result payload must reach the next model input"


def test_task_8_observation_propagation(tmp_path):
    """The exact tool result—not only a marker—reaches the next model input."""

    _assert_exact_observation_payload(run_agent)


def test_task_8_known_but_disabled_tool_is_rejected(tmp_path):
    """A known tool that is disabled for this run must be rejected."""

    workspace = FakeWorkspace("/tmp")
    responses_queue = iter(
        [
            '{"tool":"write_file","path":"x","content":"y"}',
            '{"final":"recovered"}',
        ]
    )

    result = run_agent("inspect", lambda messages: next(responses_queue), workspace)

    assert result.completed
    assert workspace.executed == []
    assert result.events[0].result.startswith("error:")
    assert "not enabled" in result.events[0].result


def test_task_9_positive_limit_fails_closed(tmp_path):
    """AgentLimits rejects non-positive budgets that disable stopping."""

    from .tiny_llm_base import AgentLimits

    for kwargs in (
        {"max_steps": 0},
        {"max_context_chars": 0},
        {"max_invalid_actions": 0},
        {"max_identical_actions": 0},
    ):
        try:
            AgentLimits(**kwargs)
        except ValueError as error:
            assert "positive" in str(error)
        else:
            assert False, f"expected AgentLimits({kwargs}) to be rejected"


def test_task_9_context_limit_stops_the_loop(tmp_path):
    """An oversized context stops the loop with a context_limit reason."""

    from .tiny_llm_base import AgentLimits

    workspace = FakeWorkspace("/tmp")

    result = run_agent(
        "inspect",
        lambda _messages: '{"tool":"read_file","path":"README.md"}',
        workspace,
        AgentLimits(max_steps=3, max_context_chars=10),
    )

    assert not result.completed
    assert result.reason == "context_limit"


def test_task_9_invalid_action_limit_stops_the_loop(tmp_path):
    """Repeated invalid JSON stops the loop with invalid_action_limit."""

    from .tiny_llm_base import AgentLimits

    workspace = FakeWorkspace("/tmp")

    result = run_agent(
        "inspect",
        lambda _messages: "not json",
        workspace,
        AgentLimits(max_steps=5, max_invalid_actions=2),
    )

    assert not result.completed
    assert result.reason == "invalid_action_limit"


class _Tokenizer:
    eos_token_id = 0

    def __init__(self):
        self.template_calls = []
        self.encode_calls = []
        self.decoded = []

    def apply_chat_template(self, messages, **kwargs):
        self.template_calls.append(([dict(message) for message in messages], kwargs))
        return "rendered prompt"

    def encode(self, prompt, *, add_special_tokens):
        self.encode_calls.append((prompt, add_special_tokens))
        return [10, 11, 12]

    def decode(self, tokens):
        self.decoded.append(list(tokens))
        return "decoded:" + ",".join(str(token) for token in tokens)


class _Cache:
    def __init__(self):
        self.releases = 0

    def release(self):
        self.releases += 1


class _TokenModel:
    def __init__(self, tokens):
        self.tokens = iter(tokens)
        self.calls = []

    def __call__(self, tokens, offset, caches):
        token = next(self.tokens)
        self.calls.append((tokens.tolist(), offset, tuple(caches)))
        row = [-1.0] * 128
        row[token] = 1.0
        return mx.array([[row] * int(tokens.size)])


def test_task_10_generation_uses_the_exact_prompt_offsets_eos_and_releases():
    messages = [{"role": "user", "content": "finish the task"}]
    tokenizer = _Tokenizer()
    model = _TokenModel((65, 66, tokenizer.eos_token_id))
    caches = (_Cache(), _Cache())

    result = generate_response(
        model,
        tokenizer,
        messages,
        lambda: caches,
        max_tokens=5,
        enable_thinking=True,
    )

    assert result == "decoded:65,66"
    assert tokenizer.template_calls == [
        (
            messages,
            {
                "tokenize": False,
                "add_generation_prompt": True,
                "enable_thinking": True,
            },
        )
    ]
    assert tokenizer.encode_calls == [("rendered prompt", False)]
    assert tokenizer.decoded == [[65, 66]]
    assert [(tokens, offset) for tokens, offset, _ in model.calls] == [
        ([[10, 11, 12]], 0),
        ([[65]], 3),
        ([[66]], 4),
    ]
    assert all(call_caches == caches for _, _, call_caches in model.calls)
    assert [cache.releases for cache in caches] == [1, 1]


def test_task_10_generation_is_bounded_and_uses_one_fresh_cache_per_call():
    tokenizer = _Tokenizer()
    created = []

    def cache_factory():
        cache = _Cache()
        created.append(cache)
        return (cache,)

    with pytest.raises(ValueError, match="max_tokens must be positive"):
        generate_response(_TokenModel((7,)), tokenizer, [], cache_factory, max_tokens=0)
    assert created == []

    first = generate_response(
        _TokenModel((7, 8, 9)), tokenizer, [], cache_factory, max_tokens=2
    )
    second = generate_response(
        _TokenModel((9,)), tokenizer, [], cache_factory, max_tokens=1
    )

    assert first == "decoded:7,8"
    assert second == "decoded:9"
    assert len(created) == 2 and created[0] is not created[1]
    assert [cache.releases for cache in created] == [1, 1]


def test_task_10_generation_releases_every_cache_when_the_model_fails():
    tokenizer = _Tokenizer()
    caches = (_Cache(), _Cache())

    def fail_model(*_args):
        raise RuntimeError("model failed")

    with pytest.raises(RuntimeError, match="model failed"):
        generate_response(fail_model, tokenizer, [], lambda: caches, max_tokens=1)

    assert [cache.releases for cache in caches] == [1, 1]
