# WARNING: Under review - generated by LLM.

"""Week 4 Day 5 receipt-backed context-compaction course-code tests."""

import json

import pytest

from .tiny_llm_base import (
    EffectReceipt,
    FinalAction,
    compact_completed_interactions,
    parse_action,
)


def _count_fake_tokens(messages):
    """Use Day 5's local deterministic message-content character counter."""

    return sum(len(message["content"]) for message in messages)


def _completed_effects():
    command_result = "status: 0\noutput:\n" + "validation detail\n" * 200
    command = EffectReceipt(
        "call-1",
        "run_command",
        {"argv": ["python", "validate.py"]},
        "ok",
        command_result,
    )
    edit = EffectReceipt(
        "call-2",
        "edit_file",
        {"path": "app.py", "old": "1", "new": "2"},
        "ok",
        "edited app.py",
        ("app.py",),
    )
    messages = [
        {"role": "system", "content": "Use one JSON action."},
        {"role": "user", "content": "Fix and validate app.py."},
        {
            "role": "assistant",
            "content": json.dumps({"tool": command.tool, **command.arguments}),
        },
        {"role": "user", "content": f"Tool result:\n{command.result}"},
        {
            "role": "assistant",
            "content": json.dumps({"tool": edit.tool, **edit.arguments}),
        },
        {"role": "user", "content": f"Tool result:\n{edit.result}"},
    ]
    return messages, command, edit


def test_task_1_compacts_old_effect_and_keeps_recent_interaction_visible():
    messages, command, edit = _completed_effects()

    result = compact_completed_interactions(
        messages,
        (command, edit),
        _count_fake_tokens,
        keep_recent=1,
        result_preview_chars=80,
    )

    assert result.compacted_interactions == 1
    assert result.receipt_ids == (command.receipt_id,)
    assert result.tokens_before == _count_fake_tokens(messages)
    assert result.tokens_after == _count_fake_tokens(list(result.messages))
    assert result.saved_tokens > 0
    assert result.messages[:2] == tuple(messages[:2])
    assert result.messages[-2:] == tuple(messages[-2:])


def test_task_2_compact_record_retains_the_evidence_needed_for_a_final_answer():
    messages, command, edit = _completed_effects()

    result = compact_completed_interactions(
        messages,
        (command, edit),
        _count_fake_tokens,
        keep_recent=1,
        result_preview_chars=80,
    )
    compacted = result.messages[3]["content"]

    assert "Completed tool interaction (compacted evidence)" in compacted
    assert result.messages[2] == messages[2]
    assert result.messages[3]["role"] == "user"
    assert command.receipt_id in compacted
    assert '"tool":"run_command"' in compacted
    assert '"exit_state":"ok"' in compacted
    assert '"changed_artifacts":[]' in compacted
    assert '"result_preview":"status: 0' in compacted
    assert "chars omitted" in compacted
    assert command.result not in compacted
    assert command.result.endswith("validation detail\n")


def test_task_3_requires_exact_receipt_evidence_and_preserves_the_input():
    messages, command, _edit = _completed_effects()
    before = [dict(message) for message in messages]
    mismatches = (
        EffectReceipt(
            command.tool_call_id,
            "edit_file",
            command.arguments,
            command.exit_state,
            command.result,
        ),
        EffectReceipt(
            command.tool_call_id,
            command.tool,
            {"argv": ["python", "other.py"]},
            command.exit_state,
            command.result,
        ),
        EffectReceipt(
            command.tool_call_id,
            command.tool,
            command.arguments,
            command.exit_state,
            "different result",
        ),
    )

    for mismatched in mismatches:
        result = compact_completed_interactions(
            messages, (mismatched,), _count_fake_tokens, keep_recent=0
        )
        assert result.compacted_interactions == 0
        assert list(result.messages) == before
    assert messages == before


def test_task_4_leaves_unreceipted_tool_observations_verbatim():
    result_text = "project fact\n" * 200
    messages = [
        {"role": "system", "content": "system"},
        {"role": "user", "content": "inspect"},
        {
            "role": "assistant",
            "content": '{"tool":"read_file","path":"README.md"}',
        },
        {"role": "user", "content": f"Tool result:\n{result_text}"},
    ]

    result = compact_completed_interactions(
        messages, (), _count_fake_tokens, keep_recent=0
    )

    assert result.compacted_interactions == 0
    assert list(result.messages) == messages
    assert result.saved_tokens == 0

    incomplete = [
        *messages[:2],
        {
            "role": "assistant",
            "content": '{"tool":"run_command","argv":["python","validate.py"]}',
        },
    ]
    result = compact_completed_interactions(
        incomplete,
        (_completed_effects()[1],),
        _count_fake_tokens,
        keep_recent=0,
    )
    assert result.compacted_interactions == 0
    assert list(result.messages) == incomplete


def test_task_5_compacted_view_continues_through_the_existing_model_protocol():
    messages, command, edit = _completed_effects()
    result = compact_completed_interactions(
        messages,
        (command, edit),
        _count_fake_tokens,
        keep_recent=1,
        result_preview_chars=80,
    )
    seen = []

    def generate(model_messages):
        seen.extend(model_messages)
        return '{"final":"app.py was edited and validation passed"}'

    response = generate([dict(message) for message in result.messages])
    action = parse_action(response, frozenset())

    assert isinstance(action, FinalAction)
    assert action.final == "app.py was edited and validation passed"
    assert command.receipt_id in seen[3]["content"]


def test_task_6_compaction_is_idempotent_and_validates_its_small_policy():
    messages, command, edit = _completed_effects()
    first = compact_completed_interactions(
        messages,
        (command, edit),
        _count_fake_tokens,
        keep_recent=1,
        result_preview_chars=80,
    )
    second = compact_completed_interactions(
        list(first.messages),
        (command, edit),
        _count_fake_tokens,
        keep_recent=0,
        result_preview_chars=80,
    )

    assert second.compacted_interactions == 0
    assert second.messages == first.messages
    no_savings = compact_completed_interactions(
        messages, (command, edit), lambda _messages: 10, keep_recent=0
    )
    assert no_savings.compacted_interactions == 0
    assert no_savings.tokens_before == no_savings.tokens_after == 10
    with pytest.raises(ValueError, match="keep_recent"):
        compact_completed_interactions(messages, (), _count_fake_tokens, keep_recent=-1)
    with pytest.raises(ValueError, match="result_preview_chars"):
        compact_completed_interactions(
            messages, (), _count_fake_tokens, result_preview_chars=0
        )
    with pytest.raises(ValueError, match="count_tokens"):
        compact_completed_interactions(messages, (), lambda _messages: True)
